export const mockData = {
  politicos: [
    {
      id: "a1",
      nome_urna: "Deputado José Silva",
      cargo: "Deputado",
      partido: "PL",
      uf: "SP",
      foto_url: "https://i.pravatar.cc/150?u=a1",
      tags_ia: ["Pró-Educação", "Infraestrutura"],
      despesas_mes: 32400.0,
      presenca_pct: 98,
      isFavorito: true,
    },
    {
      id: "a2",
      nome_urna: "Dep. Maria Oliveira",
      cargo: "Deputado",
      partido: "PT",
      uf: "RJ",
      foto_url: "https://i.pravatar.cc/150?u=a2",
      tags_ia: ["Saúde", "Direitos Humanos"],
      despesas_mes: 41500.0,
      presenca_pct: 85,
      isFavorito: false,
    },
    {
      id: "a3",
      nome_urna: "Senador Carlos Mendes",
      cargo: "Senador",
      partido: "MDB",
      uf: "MG",
      foto_url: "https://i.pravatar.cc/150?u=a3",
      tags_ia: ["Agropecuária", "Economia"],
      despesas_mes: 28100.0,
      presenca_pct: 92,
      isFavorito: false,
    },
    {
      id: "a4",
      nome_urna: "Dep. Ana Paula",
      cargo: "Deputado",
      partido: "PSDB",
      uf: "RS",
      foto_url: "https://i.pravatar.cc/150?u=a4",
      tags_ia: ["Economia", "Segurança"],
      despesas_mes: 35500.0,
      presenca_pct: 100,
      isFavorito: false,
    },
  ],
  projetos_recentes: [
    {
      id: "p1",
      autor_id: "a1",
      numero: "PL 452/2024",
      titulo: "Incentivo a Escolas Técnicas",
      resumo_ia: "Propõe redução de impostos para empresas que financiarem laboratórios em escolas públicas de nível técnico.",
      dias_atras: 2,
    },
    {
      id: "p2",
      autor_id: "a1",
      numero: "PL 128/2024",
      titulo: "Transparência em Obras",
      resumo_ia: "Obriga a atualização em tempo real do custo de obras públicas em rodovias federais por meio de aplicativo.",
      dias_atras: 7,
    },
  ],
  feed_favoritos: [
    {
      id: "f1",
      politico: { nome: "Deputado José Silva", foto: "https://i.pravatar.cc/150?u=a1" },
      tipo: "Projeto de Lei",
      titulo: "Protocolou um novo projeto de lei sobre Educação básica e infraestrutura.",
      tempo: "2h atrás",
      likes: 124,
      comments: 12,
    },
    {
      id: "f2",
      politico: { nome: "Senadora Maria Santos", foto: "https://i.pravatar.cc/150?u=a5" },
      tipo: "Transparência",
      titulo: "Publicou a prestação de contas e gastos parlamentares de Janeiro.",
      tempo: "Ontem",
      likes: 88,
      comments: 45,
    },
  ]
}
